"""Stock universes.

Two kinds live here. ``SECTORS`` holds hand-typed S&P 500 constituents by GICS sector, used for
the cross-sector screen that motivated the project. ``universes/*.json`` holds universes built by
:mod:`pairs_trading.universe_selection` (for example ``utilities_top50``: the 50 largest US
utilities by market cap with a full price history), which is the project's default universe.

Pairs are only screened *within* a sector. Same-sector pairs have an economic reason to be
cointegrated (shared factor exposure) and restricting to them shrinks the number of hypothesis
tests, which matters because Engle-Granger screening at p < 0.05 across thousands of unrelated
pairs would produce hundreds of false positives by chance alone.

Known limitation (survivorship bias): these are constituents as of 2024. Companies that were in
the index in 2019 but were later delisted, acquired or removed are not represented. Free data
sources cannot easily fix this, so it is documented rather than solved.

Symbols that Yahoo Finance no longer serves under their 2024 ticker (BK, CTRA, HES and MMC as of
September 2026, renamed or acquired) are left out so the default run is clean. Any symbol that
breaks in future is dropped by the cleaning step with a warning rather than crashing the run.
"""

import json
from collections.abc import Iterable
from functools import cache
from pathlib import Path

UNIVERSE_DIR = Path(__file__).parent / "universes"

SECTORS: dict[str, tuple[str, ...]] = {
    "energy": (
        "APA",
        "BKR",
        "COP",
        "CVX",
        "DVN",
        "EOG",
        "EQT",
        "FANG",
        "HAL",
        "KMI",
        "MPC",
        "OKE",
        "OXY",
        "PSX",
        "SLB",
        "TRGP",
        "VLO",
        "WMB",
        "XOM",
    ),
    "financials": (
        # Banks
        "BAC",
        "C",
        "CFG",
        "COF",
        "FITB",
        "GS",
        "HBAN",
        "JPM",
        "KEY",
        "MS",
        "MTB",
        "NTRS",
        "PNC",
        "RF",
        "STT",
        "TFC",
        "USB",
        "WFC",
        "ZION",
        # Insurance
        "AFL",
        "AIG",
        "ALL",
        "CB",
        "MET",
        "PGR",
        "PRU",
        "TRV",
        # Asset management, exchanges, data and payments
        "AJG",
        "AMP",
        "AON",
        "AXP",
        "BLK",
        "CME",
        "ICE",
        "MA",
        "MCO",
        "MSCI",
        "NDAQ",
        "SCHW",
        "SPGI",
        "TROW",
        "V",
    ),
    "utilities": (
        "AEE",
        "AEP",
        "AES",
        "ATO",
        "AWK",
        "CMS",
        "CNP",
        "D",
        "DTE",
        "DUK",
        "ED",
        "EIX",
        "ES",
        "ETR",
        "EVRG",
        "EXC",
        "FE",
        "LNT",
        "NEE",
        "NI",
        "NRG",
        "PEG",
        "PNW",
        "PPL",
        "SO",
        "SRE",
        "WEC",
        "XEL",
    ),
}


@cache
def json_universes() -> dict[str, dict[str, object]]:
    """Universes generated by :mod:`pairs_trading.universe_selection`, keyed by name.

    Each ``universes/<name>.json`` records the selection criteria, the chosen tickers and the
    excluded candidates, so a claim like "top 50 by market cap" is auditable.
    """
    specs: dict[str, dict[str, object]] = {}
    if UNIVERSE_DIR.is_dir():
        for path in sorted(UNIVERSE_DIR.glob("*.json")):
            spec = json.loads(path.read_text(encoding="utf-8"))
            specs[str(spec.get("name", path.stem)).lower()] = spec
    return specs


def available_sectors() -> list[str]:
    return sorted(set(SECTORS) | set(json_universes()))


def universe_spec(name: str) -> dict[str, object] | None:
    """The JSON selection record for a generated universe, or ``None`` for a hardcoded one."""
    return json_universes().get(name.lower())


def _tickers_for(key: str) -> tuple[str, ...]:
    if key in SECTORS:
        return SECTORS[key]
    spec = json_universes().get(key)
    if spec is None:
        raise KeyError(f"unknown sector {key!r}; available: {available_sectors()}")
    return tuple(dict.fromkeys(str(t) for t in spec["tickers"]))


def get_universe(sectors: Iterable[str]) -> dict[str, str]:
    """Return ``{ticker: sector}`` for the requested sectors (hardcoded or generated).

    Raises ``KeyError`` naming the unknown sector and the available ones, and ``ValueError`` if
    a ticker belongs to two of the requested sectors: pairs are only screened within a sector,
    so overlapping universes (``utilities_top50`` contains every hardcoded ``utilities`` ticker)
    would silently split the tickers by label and drop the cross-label pairs.
    """
    universe: dict[str, str] = {}
    for sector in sectors:
        key = sector.lower()
        for ticker in _tickers_for(key):
            previous = universe.get(ticker)
            if previous is not None and previous != key:
                raise ValueError(
                    f"ticker {ticker} is in both {previous!r} and {key!r}; overlapping "
                    "universes cannot be combined, pick one"
                )
            universe[ticker] = key
    return universe
